notifications:
  commits: site-pub@tomee.apache.org
  issues: site-pub@tomee.apache.org
  pullrequests: site-pub@tomee.apache.org
  jira_options: link label link label

# this staging config will publish any commits to https://tomee-beta.staged.apache.org
staging:
  profile: md2adoc
  whoami: md2adoc
