notifications:
  commits: site-pub@tomee.apache.org
  issues: site-pub@tomee.apache.org
  pullrequests: site-pub@tomee.apache.org
  jira_options: link label

publish:
  whoami: asf-site

# this staging config will publish any commits to https://tomee-beta.staged.apache.org
staging:
  whoami: md2adoc
github:
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
